apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  namespace: cronjob
  labels:
    app: kubectl
spec:
  serviceAccountName: kubectl
  restartPolicy: Always
  containers:
    - name: kubectl
      image: docker.io/bitnami/kubectl:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
